import 'package:flutter/material.dart';

// 图标分类模型
class IconCategory {
  final String name;
  final IconData icon;
  final List<IconData> icons;

  const IconCategory({
    required this.name,
    required this.icon,
    required this.icons,
  });
}

// 图标管理类
class HabitIcons {
  // 图标分类数据
  static const List<IconCategory> categories = [
    IconCategory(
      name: '常用',
      icon: Icons.star_outline,
      icons: [
        Icons.flag_outlined,
        Icons.star_outline,
        Icons.favorite_outline,
        Icons.bookmark_outline,
        Icons.push_pin_outlined,
        Icons.lightbulb_outline,
        Icons.check_circle_outline,
        Icons.radio_button_checked,
        Icons.task_alt_outlined,
        Icons.verified_outlined,
        Icons.thumb_up_outlined,
        Icons.grade_outlined,
      ],
    ),
    IconCategory(
      name: '时间',
      icon: Icons.schedule_outlined,
      icons: [
        Icons.wb_sunny_outlined,
        Icons.bedtime_outlined,
        Icons.alarm_outlined,
        Icons.timer_outlined,
        Icons.schedule_outlined,
        Icons.nightlight_outlined,
        Icons.wb_twilight_outlined,
        Icons.hourglass_empty_outlined,
        Icons.update_outlined,
        Icons.history_outlined,
      ],
    ),
    IconCategory(
      name: '运动',
      icon: Icons.fitness_center,
      icons: [
        Icons.fitness_center,
        Icons.directions_run,
        Icons.directions_walk,
        Icons.sports_gymnastics,
        Icons.pool_outlined,
        Icons.pedal_bike_outlined,
        Icons.skateboarding_outlined,
        Icons.surfing_outlined,
        Icons.hiking_outlined,
        Icons.sports_martial_arts,
        Icons.sports_soccer_outlined,
        Icons.sports_basketball_outlined,
        Icons.sports_tennis_outlined,
        Icons.sports_golf_outlined,
        Icons.sports_baseball_outlined,
        Icons.snowboarding_outlined,
        Icons.downhill_skiing_outlined,
        Icons.rowing_outlined,
        Icons.kayaking_outlined,
        Icons.sports_handball_outlined,
        Icons.sports_volleyball_outlined,
        Icons.sports_cricket_outlined,
        Icons.sports_rugby_outlined,
        Icons.sports_kabaddi_outlined,
        Icons.sports_mma_outlined,
      ],
    ),
    IconCategory(
      name: '饮食',
      icon: Icons.restaurant_outlined,
      icons: [
        Icons.water_drop_outlined,
        Icons.local_drink_outlined,
        Icons.coffee_outlined,
        Icons.local_cafe_outlined,
        Icons.free_breakfast_outlined,
        Icons.wine_bar_outlined,
        Icons.no_drinks_outlined,
        Icons.restaurant_outlined,
        Icons.apple,
        Icons.egg_outlined,
        Icons.rice_bowl_outlined,
        Icons.ramen_dining_outlined,
        Icons.lunch_dining_outlined,
        Icons.dinner_dining_outlined,
        Icons.bakery_dining_outlined,
        Icons.icecream_outlined,
        Icons.cookie_outlined,
        Icons.cake_outlined,
        Icons.local_pizza_outlined,
        Icons.set_meal_outlined,
        Icons.no_food_outlined,
        Icons.no_meals_outlined,
        Icons.fastfood_outlined,
        Icons.kebab_dining_outlined,
        Icons.soup_kitchen_outlined,
      ],
    ),
    IconCategory(
      name: '学习',
      icon: Icons.menu_book_outlined,
      icons: [
        Icons.menu_book_outlined,
        Icons.auto_stories_outlined,
        Icons.book_outlined,
        Icons.library_books_outlined,
        Icons.article_outlined,
        Icons.edit_note,
        Icons.draw_outlined,
        Icons.edit_outlined,
        Icons.history_edu_outlined,
        Icons.school_outlined,
        Icons.science_outlined,
        Icons.calculate_outlined,
        Icons.functions_outlined,
        Icons.biotech_outlined,
        Icons.psychology_outlined,
        Icons.architecture_outlined,
        Icons.precision_manufacturing_outlined,
      ],
    ),
    IconCategory(
      name: '语言',
      icon: Icons.translate,
      icons: [
        Icons.translate,
        Icons.language_outlined,
        Icons.abc_outlined,
        Icons.spellcheck_outlined,
        Icons.record_voice_over_outlined,
        Icons.mic_outlined,
        Icons.headphones_outlined,
        Icons.hearing_outlined,
        Icons.interpreter_mode_outlined,
        Icons.subtitles_outlined,
        Icons.closed_caption_outlined,
        Icons.speaker_notes_outlined,
      ],
    ),
    IconCategory(
      name: '工作',
      icon: Icons.work_outline,
      icons: [
        Icons.code,
        Icons.terminal_outlined,
        Icons.computer_outlined,
        Icons.work_outline,
        Icons.business_center_outlined,
        Icons.task_alt_outlined,
        Icons.checklist_outlined,
        Icons.fact_check_outlined,
        Icons.assignment_outlined,
        Icons.pending_actions_outlined,
        Icons.event_outlined,
        Icons.event_available_outlined,
        Icons.inbox_outlined,
        Icons.mail_outlined,
        Icons.send_outlined,
        Icons.analytics_outlined,
        Icons.insights_outlined,
        Icons.trending_up_outlined,
        Icons.assessment_outlined,
        Icons.leaderboard_outlined,
        Icons.bar_chart_outlined,
        Icons.show_chart_outlined,
      ],
    ),
    IconCategory(
      name: '艺术',
      icon: Icons.palette_outlined,
      icons: [
        Icons.music_note_outlined,
        Icons.piano_outlined,
        Icons.album_outlined,
        Icons.library_music_outlined,
        Icons.queue_music_outlined,
        Icons.brush_outlined,
        Icons.palette_outlined,
        Icons.format_paint_outlined,
        Icons.gesture_outlined,
        Icons.auto_fix_high_outlined,
        Icons.photo_filter_outlined,
        Icons.filter_vintage_outlined,
        Icons.theater_comedy_outlined,
      ],
    ),
    IconCategory(
      name: '摄影',
      icon: Icons.camera_alt_outlined,
      icons: [
        Icons.camera_alt_outlined,
        Icons.videocam_outlined,
        Icons.movie_outlined,
        Icons.theaters_outlined,
        Icons.tv_outlined,
        Icons.podcasts_outlined,
        Icons.live_tv_outlined,
        Icons.photo_outlined,
        Icons.photo_library_outlined,
        Icons.video_library_outlined,
        Icons.slideshow_outlined,
        Icons.camera_roll_outlined,
      ],
    ),
    IconCategory(
      name: '心灵',
      icon: Icons.self_improvement,
      icons: [
        Icons.self_improvement,
        Icons.psychology_outlined,
        Icons.spa_outlined,
        Icons.hot_tub_outlined,
        Icons.air_outlined,
        Icons.mood_outlined,
        Icons.sentiment_satisfied_outlined,
        Icons.emoji_emotions_outlined,
        Icons.emoji_nature_outlined,
        Icons.volunteer_activism_outlined,
        Icons.diversity_1_outlined,
        Icons.handshake_outlined,
        Icons.favorite_outline,
        Icons.healing_outlined,
        Icons.church_outlined,
        Icons.temple_buddhist_outlined,
      ],
    ),
    IconCategory(
      name: '生活',
      icon: Icons.home_outlined,
      icons: [
        Icons.cleaning_services_outlined,
        Icons.dry_cleaning_outlined,
        Icons.iron_outlined,
        Icons.checkroom_outlined,
        Icons.bathtub_outlined,
        Icons.shower_outlined,
        Icons.wash_outlined,
        Icons.soap_outlined,
        Icons.sanitizer_outlined,
        Icons.face_retouching_natural_outlined,
        Icons.face_outlined,
        Icons.home_outlined,
        Icons.bed_outlined,
        Icons.chair_outlined,
        Icons.weekend_outlined,
        Icons.kitchen_outlined,
        Icons.bathroom_outlined,
        Icons.living_outlined,
      ],
    ),
    IconCategory(
      name: '自然',
      icon: Icons.eco_outlined,
      icons: [
        Icons.local_florist_outlined,
        Icons.grass_outlined,
        Icons.yard_outlined,
        Icons.eco_outlined,
        Icons.park_outlined,
        Icons.forest_outlined,
        Icons.pets_outlined,
        Icons.cruelty_free_outlined,
        Icons.bug_report_outlined,
        Icons.emoji_nature_outlined,
        Icons.waves_outlined,
        Icons.terrain_outlined,
        Icons.landscape_outlined,
        Icons.water_outlined,
        Icons.cloud_outlined,
        Icons.thunderstorm_outlined,
        Icons.ac_unit_outlined,
        Icons.wb_cloudy_outlined,
      ],
    ),
    IconCategory(
      name: '社交',
      icon: Icons.people_outline,
      icons: [
        Icons.people_outline,
        Icons.person_outline,
        Icons.groups_outlined,
        Icons.family_restroom_outlined,
        Icons.elderly_outlined,
        Icons.child_care_outlined,
        Icons.call_outlined,
        Icons.video_call_outlined,
        Icons.chat_outlined,
        Icons.forum_outlined,
        Icons.campaign_outlined,
        Icons.connect_without_contact_outlined,
        Icons.share_outlined,
        Icons.group_add_outlined,
        Icons.person_add_outlined,
        Icons.waving_hand_outlined,
      ],
    ),
    IconCategory(
      name: '出行',
      icon: Icons.explore_outlined,
      icons: [
        Icons.directions_car_outlined,
        Icons.directions_bus_outlined,
        Icons.train_outlined,
        Icons.flight_outlined,
        Icons.flight_takeoff_outlined,
        Icons.two_wheeler_outlined,
        Icons.electric_scooter_outlined,
        Icons.sailing_outlined,
        Icons.explore_outlined,
        Icons.map_outlined,
        Icons.tour_outlined,
        Icons.luggage_outlined,
        Icons.directions_bike_outlined,
        Icons.directions_subway_outlined,
        Icons.local_taxi_outlined,
        Icons.airport_shuttle_outlined,
        Icons.directions_boat_outlined,
        Icons.rocket_launch_outlined,
      ],
    ),
    IconCategory(
      name: '健康',
      icon: Icons.monitor_heart_outlined,
      icons: [
        Icons.medical_services_outlined,
        Icons.medication_outlined,
        Icons.vaccines_outlined,
        Icons.healing_outlined,
        Icons.health_and_safety_outlined,
        Icons.monitor_heart_outlined,
        Icons.bloodtype_outlined,
        Icons.visibility_outlined,
        Icons.hearing_outlined,
        Icons.accessibility_new_outlined,
        Icons.monitor_weight_outlined,
        Icons.sick_outlined,
        Icons.coronavirus_outlined,
        Icons.masks_outlined,
        Icons.personal_injury_outlined,
        Icons.emergency_outlined,
      ],
    ),
    IconCategory(
      name: '财务',
      icon: Icons.savings_outlined,
      icons: [
        Icons.savings_outlined,
        Icons.account_balance_wallet_outlined,
        Icons.payments_outlined,
        Icons.credit_card_outlined,
        Icons.attach_money_outlined,
        Icons.money_off_outlined,
        Icons.receipt_long_outlined,
        Icons.account_balance_outlined,
        Icons.currency_exchange_outlined,
        Icons.price_check_outlined,
        Icons.request_quote_outlined,
        Icons.point_of_sale_outlined,
        Icons.monetization_on_outlined,
      ],
    ),
    IconCategory(
      name: '数码',
      icon: Icons.devices_outlined,
      icons: [
        Icons.phone_android_outlined,
        Icons.phone_iphone_outlined,
        Icons.phone_disabled_outlined,
        Icons.smartphone_outlined,
        Icons.tablet_outlined,
        Icons.watch_outlined,
        Icons.devices_outlined,
        Icons.battery_charging_full_outlined,
        Icons.power_outlined,
        Icons.wifi_off_outlined,
        Icons.bluetooth_outlined,
        Icons.screen_lock_portrait_outlined,
        Icons.do_not_disturb_on_outlined,
        Icons.data_saver_on_outlined,
        Icons.signal_cellular_alt_outlined,
      ],
    ),
    IconCategory(
      name: '娱乐',
      icon: Icons.sports_esports_outlined,
      icons: [
        Icons.sports_esports_outlined,
        Icons.games_outlined,
        Icons.casino_outlined,
        Icons.extension_outlined,
        Icons.toys_outlined,
        Icons.attractions_outlined,
        Icons.celebration_outlined,
        Icons.party_mode_outlined,
        Icons.nightlife_outlined,
        Icons.local_bar_outlined,
        Icons.music_video_outlined,
        Icons.stadium_outlined,
        Icons.festival_outlined,
        Icons.event_seat_outlined,
        Icons.confirmation_number_outlined,
      ],
    ),
    IconCategory(
      name: '成就',
      icon: Icons.emoji_events_outlined,
      icons: [
        Icons.emoji_events_outlined,
        Icons.military_tech_outlined,
        Icons.diamond_outlined,
        Icons.bolt_outlined,
        Icons.public_outlined,
        Icons.verified_outlined,
        Icons.workspace_premium_outlined,
        Icons.stars_outlined,
        Icons.auto_awesome_outlined,
        Icons.flare_outlined,
        Icons.whatshot_outlined,
        Icons.local_fire_department_outlined,
        Icons.shield_outlined,
        Icons.security_outlined,
        Icons.token_outlined,
      ],
    ),
  ];

  // 获取所有图标的平铺列表（用于索引存储）
  static List<IconData> get allIcons {
    final List<IconData> icons = [];
    for (final category in categories) {
      for (final icon in category.icons) {
        if (!icons.contains(icon)) {
          icons.add(icon);
        }
      }
    }
    return icons;
  }

  static IconData getIcon(int index) {
    final icons = allIcons;
    if (index >= 0 && index < icons.length) {
      return icons[index];
    }
    return Icons.flag_outlined;
  }

  static int getIconIndex(IconData icon) {
    return allIcons.indexOf(icon);
  }
}